name: Publish site

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE_ARN:
        required: true
      AWS_BUCKET_NAME:
        required: true

jobs:
  publish-site:
    name: Publish site
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Run build script
        run: yarn build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ghactionssession
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to `${{ inputs.destination_dir }}` directory of remote storage
        run: |
          aws s3 cp ./public s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.destination_dir }} --recursive --acl private
