name: Publish Release

on:
  workflow_call:
    secrets:
      METAMASKBOT_TOKEN:
        required: true

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: MetaMask/action-publish-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  get-release-version:
    runs-on: ubuntu-latest
    needs: publish-release
    outputs:
      RELEASE_VERSION: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - id: get-release-version
        shell: bash
        run: ./scripts/get.sh ".version" "RELEASE_VERSION"

  publish-release-to-gh-pages:
    needs: get-release-version
    name: Publish site to `${{ needs.get-release-version.outputs.RELEASE_VERSION }}` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: ${{ needs.get-release-version.outputs.RELEASE_VERSION }}
    secrets:
      METAMASKBOT_TOKEN: ${{ secrets.METAMASKBOT_TOKEN }}
